table model_comparison

	measure 'Selected Model Accuracy' = CALCULATE(MAX(model_comparison[Accuracy]), model_comparison[Model] = "Random Forest")
		formatString: 0.00%

	measure 'Selected Model Precision' = CALCULATE(MAX(model_comparison[Precision]), model_comparison[Model] = "Random Forest")
		formatString: 0.00%

	measure 'Selected Model Recall' = CALCULATE(MAX(model_comparison[Recall]), model_comparison[Model] = "Random Forest")
		formatString: 0.00%

	measure 'Selected Model F1' = CALCULATE(MAX(model_comparison[F1]), model_comparison[Model] = "Random Forest")
		formatString: 0.00%

	measure 'Selected Model ROC AUC' = CALCULATE(MAX(model_comparison[ROC_AUC]), model_comparison[Model] = "Random Forest")
		formatString: 0.00%

	measure 'Selected Model PR AUC' = CALCULATE(MAX(model_comparison[PR_AUC]), model_comparison[Model] = "Random Forest")
		formatString: 0.00%

	measure 'Model ROC AUC' = MAX(model_comparison[ROC_AUC])
		formatString: 0.00%

	measure 'Model PR AUC' = MAX(model_comparison[PR_AUC])
		formatString: 0.00%

	measure 'Model Recall' = MAX(model_comparison[Recall])
		formatString: 0.00%

	measure 'Model Precision' = MAX(model_comparison[Precision])
		formatString: 0.00%

	measure 'Model F1' = MAX(model_comparison[F1])
		formatString: 0.00%

	column Model
		dataType: string
		sourceColumn: Model
		summarizeBy: none

	column Accuracy
		dataType: double
		formatString: 0.00%
		sourceColumn: Accuracy
		summarizeBy: none

	column Precision
		dataType: double
		formatString: 0.00%
		sourceColumn: Precision
		summarizeBy: none

	column Recall
		dataType: double
		formatString: 0.00%
		sourceColumn: Recall
		summarizeBy: none

	column F1
		dataType: double
		formatString: 0.00%
		sourceColumn: F1
		summarizeBy: none

	column ROC_AUC
		dataType: double
		formatString: 0.00%
		sourceColumn: ROC_AUC
		summarizeBy: none

	column PR_AUC
		dataType: double
		formatString: 0.00%
		sourceColumn: PR_AUC
		summarizeBy: none

	partition model_comparison = m
		mode: import
		source =
				let
					Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/muhammadhassan8646451-design/Data-Analytics-Projects/main/05-Credit-Risk-Explainable-ML/powerbi/model_comparison.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(
						Headers,
						{
							{"Model", type text},
							{"Accuracy", type number},
							{"Precision", type number},
							{"Recall", type number},
							{"F1", type number},
							{"ROC_AUC", type number},
							{"PR_AUC", type number}
						},
						"en-US"
					)
				in
					Typed