# Stock Market Analytics Pipeline
# Generated by Hassan Project 4 notebook.

import numpy as np
import pandas as pd

def engineer_market_features(df):
    df = df.sort_values(["Ticker", "Date"]).copy()

    def _features(g):
        g = g.sort_values("Date").copy()
        g["DailyReturn"] = g["Adj Close"].pct_change()
        g["LogReturn"] = np.log(g["Adj Close"] / g["Adj Close"].shift(1))
        g["CumulativeReturn"] = (1 + g["DailyReturn"].fillna(0)).cumprod() - 1
        g["MA20"] = g["Adj Close"].rolling(20).mean()
        g["MA50"] = g["Adj Close"].rolling(50).mean()
        g["RollingVol20"] = g["DailyReturn"].rolling(20).std() * np.sqrt(252)
        g["RunningPeak"] = g["Adj Close"].cummax()
        g["Drawdown"] = g["Adj Close"] / g["RunningPeak"] - 1
        return g

    return (
        df.groupby("Ticker", group_keys=False)
          .apply(_features)
          .reset_index(drop=True)
    )
