# Customer Churn Prediction Pipeline
# Generated by Hassan Project 3 notebook.

from pathlib import Path
import pandas as pd
import numpy as np
import joblib

def load_model(model_path="models/best_churn_model.pkl"):
    return joblib.load(model_path)

def score_customers(model, feature_df):
    probability = model.predict_proba(feature_df)[:, 1]
    prediction = (probability >= 0.50).astype(int)

    result = feature_df.copy()
    result["ChurnProbability"] = probability
    result["PredictedChurn"] = np.where(prediction == 1, "Yes", "No")
    result["RiskBand"] = pd.cut(
        result["ChurnProbability"],
        bins=[-0.001, 0.30, 0.60, 1.0],
        labels=["Low Risk", "Medium Risk", "High Risk"],
        include_lowest=True,
        right=False
    )
    return result
